# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.default]                                         # Define a profile name
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/EXk1VtDVCaeNBRAWsi7WA" # Mainnet RPC URL  
account = "mainnet-argent"
wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer

[sncast.mainnet]                                         # Mainnet profile
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/EXk1VtDVCaeNBRAWsi7WA" # Mainnet RPC URL
account = "mainnet-argent"
wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer

[accounts-file]
default = { address = "0x01BE47EbD8FCbCd4c1fB472DFd452530D86ce18b0381233836a7994154D88617", private_key = "0x02c398465e58e5ca974035d5d145faf0980e8320e126ee2b8e4b18ac7a2b5ef6" }
mainnet-argent = { address = "0x049c97B55f2eF9523B50A61E66E8749F0c1F447C3a4e46944A0ED8b2EdD305ac", private_key = "0x03cb7d630bf9b5fbf2a8746834f50621186ae2e930e1d7c54b23baa1e31c9abc" }
