# https://github.com/foundry-rs/starknet-foundry/tree/master/docs/src/projects/configuration.md 
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[profile.default]
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_8/EXk1VtDVCaeNBRAWsi7WA"

# Account configuration - DO NOT PUT PRIVATE KEYS HERE
# Use environment variables instead:
# export STARKNET_PRIVATE_KEY="your_private_key"
# export STARKNET_ACCOUNT_ADDRESS="your_account_address"

[profile.mainnet]
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/EXk1VtDVCaeNBRAWsi7WA"

# For accounts configuration, use environment variables:
# Default account should be configured through STARKNET_* environment variables
# mainnet-argent account should be configured through STARKNET_* environment variables

[[tool.sncast.account]]
name = "default"
# Configure through environment variables for security
# STARKNET_ACCOUNT_ADDRESS and STARKNET_PRIVATE_KEY

[[tool.sncast.account]] 
name = "mainnet-argent"
# Configure through environment variables for security
# STARKNET_ACCOUNT_ADDRESS and STARKNET_PRIVATE_KEY

[tool.sncast.multicall]
