# Snfoundry configuration file

[sncast.mainnet]
account = "burr_deployer"
accounts-file = "./accounts.json"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/YOUR_API_KEY_HERE"

[tool.sncast]
account = "burr_deployer"
accounts-file = "./accounts.json"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/YOUR_API_KEY_HERE" 